name: AWS Lambda CI/CD
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build DeletePost Lambda function
        run: |
          cd DeletePost
          mvn clean package -B
          cd ..

      - name: Build GetSpecificPostDetail Lambda function
        run: |
          cd GetSpecificPostDetail
          mvn clean package -B
          cd ..

      - name: Build GetPresignedUrl Lambda function
        run: |
          cd GetPresignedUrl
          mvn clean package -B
          cd ..

      - name: Build UploadPost Lambda function
        run: |
          cd UploadPost
          mvn clean package -B
          cd ..

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::730335295917:role/github-action-lambda
          aws-region: us-east-2

      - name: Create AWS Lambda Function
        run: |
          aws lambda create-function --function-name GetPresignedUrl --runtime java17 --handler com.rundong.GetPresignedUrl::handleRequest --role arn:aws:iam::730335295917:role/lambda-role --zip-file fileb://GetPresignedUrl/target/GetPresignedUrl-1.0-SNAPSHOT.jar
          aws lambda create-function --function-name UploadPost --runtime java17 --handler com.rundong.UploadPost::handleRequest --role arn:aws:iam::730335295917:role/lambda-role --zip-file fileb://UploadPost/target/UploadPost-1.0-SNAPSHOT.jar
          aws lambda create-function --function-name GetSpecificPostDetail --runtime java17 --handler com.rundong.GetSpecificPostDetail::handleRequest --role arn:aws:iam::730335295917:role/lambda-role --zip-file fileb://GetSpecificPostDetail/target/GetSpecificPostDetail-1.0-SNAPSHOT.jar
          aws lambda create-function --function-name DeletePost --runtime java17 --handler com.rundong.DeletePost::handleRequest --role arn:aws:iam::730335295917:role/lambda-role --zip-file fileb://code/backend/RentalNinja/DeletePost/target/DeletePost-1.0-SNAPSHOT.jar
          aws lambda create-function --function-name UpdateMyPostInfo --runtime java17 --handler com.rundong.UpdateMyPostInfo::handleRequest --role arn:aws:iam::730335295917:role/lambda-role --zip-file fileb://code/backend/RentalNinja/UpdateMyPostInfo/target/UpdateMyPostInfo-1.0-SNAPSHOT.jar
        continue-on-error: true

      - name: Update Lambda Function
        run: |
          aws lambda update-function-code --function-name GetPresignedUrl --zip-file fileb://GetPresignedUrl/target/GetPresignedUrl-1.0-SNAPSHOT.jar
          aws lambda update-function-code --function-name UploadPost --zip-file fileb://UploadPost/target/UploadPost-1.0-SNAPSHOT.jar
          aws lambda update-function-code --function-name GetSpecificPostDetail --zip-file fileb://GetSpecificPostDetail/target/GetSpecificPostDetail-1.0-SNAPSHOT.jar
          aws lambda update-function-code --function-name DeletePost --zip-file fileb://code/backend/RentalNinja/DeletePost/target/DeletePost-1.0-SNAPSHOT.jar
          aws lambda update-function-code --function-name UpdateMyPostInfo --zip-file fileb://code/backend/RentalNinja/UpdateMyPostInfo/target/UpdateMyPostInfo-1.0-SNAPSHOT.jar
          


