name: AWS Lambda CI/CD
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::730335295917:role/github-action-lambda
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build GetPresignedUrl Lambda function and push to ecr
        working-directory: GetPresignedUrl
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: rentalninja/get_presigned
          IMAGE_TAG: ${{ github.sha }}
        run: |
          mvn compile dependency:copy-dependencies -DincludeScope=runtime
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: MyStack
          template: cf-template.yaml
          parameter-overrides: "GetPresignedUrlImg=730335295917.dkr.ecr.us-east-2.amazonaws.com/rentalninja/get_presigned:latest,CognitoArn=arn:aws:cognito-idp:us-east-2:730335295917:userpool/us-east-2_0zgg97WG0"
          capabilities: github-action-lambda

